-- 1.)	What are the details of all cars purchased in the year 2022?

SELECT C.Car_ID, C.Make, C.Type, C.Style, C.Cost_$, YEAR(S.Purchase_Date) AS Purchase_Year
FROM Cars C
JOIN Sales S USING(Car_ID)
WHERE YEAR(S.Purchase_Date) = 2022;

-- 2.) What is the total number of cars sold by each salesperson?

SELECT
SP.Name,
COUNT(S.Sale_ID) AS Total_Sales
FROM SalesPersons SP 
JOIN Sales S USING(Salesman_ID)
GROUP BY 1
ORDER BY 2 DESC;

-- 3.) What is the total revenue generated by each salesperson?

SELECT
SP.Name,
SUM(C.Cost_$) AS Total_Revenue
FROM Salespersons SP 
JOIN Sales S USING(Salesman_ID)
JOIN Cars C USING(Car_ID)
GROUP BY 1
ORDER BY 2 DESC;

-- 4.) What are the details of the cars sold by each salesperson?

SELECT SP.Name, C.Car_ID, C.Make, C.Type, C.Style, C.Cost_$
FROM Cars C
JOIN Sales S USING(Car_ID)
JOIN SalesPersons SP USING(Salesman_ID)
ORDER BY 6 DESC;

-- 5.) What is the total revenue generated by each car type?

SELECT
Type, SUM(Cost_$) AS Total_Revenue
FROM Cars
JOIN Sales USING(Car_ID)
GROUP BY 1
ORDER BY 2 DESC;

-- 6.) What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

SELECT SP.Name, C.Car_ID, C.Make, C.Type, C.Style, C.Cost_$, YEAR(S.Purchase_Date) AS Purchase_Year
FROM Cars C 
JOIN Sales S USING(Car_ID)
JOIN SalesPersons SP USING(Salesman_ID)
WHERE YEAR(S.Purchase_Date) = 2021 AND SP.Name = "Emily Wong";

-- 7.) What is the total revenue generated by the sales of hatchback cars?

SELECT
Style, SUM(Cost_$) AS Total_Revenue
FROM Cars
JOIN Sales USING(Car_ID)
WHERE Style = "Hatchback";

-- 8.) What is the total revenue generated by the sales of SUV cars in the year 2022?

SELECT
C.Style, SUM(C.Cost_$) AS Total_Revenue, YEAR(S.Purchase_Date) AS Purchase_Year
FROM Cars C 
JOIN Sales S USING(Car_ID)
WHERE C.Style = "SUV" AND YEAR(S.Purchase_Date) = 2022
GROUP BY 1,3;

-- 9.) What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT
Name, City, Purchase_Year, Total_Sales
FROM(
	SELECT
	SP.Name, SP.City, COUNT(S.Salesman_ID) AS Total_Sales, YEAR(S.Purchase_Date) AS Purchase_Year,
	DENSE_RANK() OVER (ORDER BY COUNT(S.Salesman_ID) DESC) AS TotalSales_Dense_Rank
	FROM SalesPersons SP
	JOIN Sales S USING(Salesman_ID)
	WHERE YEAR(S.Purchase_Date) = 2023
    GROUP BY 1,2,4
) Total_Sales_Rank
WHERE TotalSales_Dense_Rank = 1;

-- 10.) What is the name and age of the salesperson who generated the highest revenue in the year 2022?

SELECT
Name, Age, Purchase_Year, Total_Revenue
FROM(
	SELECT
	SP.Name, SP.Age, SUM(C.Cost_$) AS Total_Revenue, YEAR(S.Purchase_Date) AS Purchase_Year,
	DENSE_RANK() OVER (ORDER BY COUNT(S.Salesman_ID) DESC) AS TotalRevenue_Dense_Rank
	FROM SalesPersons SP
	JOIN Sales S USING(Salesman_ID)
    JOIN Cars C USING(Car_ID)
	WHERE YEAR(S.Purchase_Date) = 2022
    GROUP BY 1,2,4
) Total_Revenue_Rank
WHERE TotalRevenue_Dense_Rank = 1;

